import type { NextPage } from 'next';
// import Head from 'next/head';
// import Image from 'next/image';
// import styles from '../styles/Home.module.scss';
import styles from './index.module.scss';

interface IProps {
  title: string;
  description: string;
  list: {
    label: string;
    info: string;
    link: string;
  }[];
}

const Home: NextPage<IProps> = ({ title, description, list }) => {
  return (
    <div className={styles.container}>
      <main className={styles.main}>
        <h1 className={styles.title}>{title}</h1>

        <p className={styles.description}>{description}</p>

        <div className={styles.grid}>
          {list?.map((item, index) => {
            return (
              <div
                key={index}
                className={styles.card}
                onClick={(): void => {
                  window.open(item.link, 'blank', 'noopener=yes,noreferrer=yes');
                }}
              >
                <h2>{item.label} &rarr;</h2>
                <p>{item.info}</p>
              </div>
            );
          })}
        </div>
      </main>
    </div>
  );
};

Home.getInitialProps = context => {
  return {
    title: 'Hello SSR!',
    description: 'A Demo for 《深入浅出SSR官网开发指南》',
    list: [
      {
        label: '文章1',
        info: 'A test for article1',
        link: 'http://localhost:3000/article/1',
      },
      {
        label: '文章2',
        info: 'A test for article2',
        link: 'http://localhost:3000/article/2',
      },
      {
        label: '文章3',
        info: 'A test for article3',
        link: 'http://localhost:3000/article/3',
      },
      {
        label: '文章4',
        info: 'A test for article4',
        link: 'http://localhost:3000/article/4',
      },
      {
        label: '文章5',
        info: 'A test for article5',
        link: 'http://localhost:3000/article/5',
      },
      {
        label: '文章6',
        info: 'A test for article6',
        link: 'http://localhost:3000/article/6',
      },
    ],
  };
};

// const Home: NextPage = () => {
//   debugger;
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name='description' content='Generated by create next app' />
//         <link rel='icon' href='/favicon.ico' />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href='https://nextjs.org'>Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing <code className={styles.code}>pages/index.tsx</code>
//         </p>

//         <div className={styles.grid}>
//           <a href='https://nextjs.org/docs' className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href='https://nextjs.org/learn' className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a href='https://github.com/vercel/next.js/tree/canary/examples' className={styles.card}>
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
//             className={styles.card}>
//             <h2>Deploy &rarr;</h2>
//             <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
//           target='_blank'
//           rel='noopener noreferrer'>
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   );
// };

export default Home;
